version: '3.3'

services:
  notary_db:
    container_name: notary_db
    image: postgres:9.6
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
  partya_db:
    container_name: partya_db
    image: postgres:9.6
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
  partyb_db:
    container_name: partyb_db
    image: postgres:9.6
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
  network-map:
    container_name: nms
    image: cordite/network-map:v0.3.7
    ports:
      - "8080:8080"
    environment:
      NMS_ROOT_CA_NAME: CN="NMS", OU=NMS-Unit, O=NMS, L=London, ST=Helsinki, C=FI
